### ISSUE TITLE
Similar library

### ISSUE THREAD

**Issue by l0kod** [shoenig/go-landlock#32]
Hi!

Nice to see such development around Landlock! FYI there is another Go library developed by @gnoack to provide a nice API for Landlock: https://github.com/landlock-lsm/go-landlock

What are the main differences between both libraries?

Would it make sense to merge them?

**Comment by shoenig** [comment]
Hi @l0kod! It seems the key difference between these two libraries is in the API they present to the caller - this one strives to be reminiscent of the OpenBSD unveil() system call. It also aims to provide convenience helpers for mainstream Linux distros for exposing things like TLS certificates, shared objects, etc. 

This library will likely be adopted by my employer's org in the near future. We've started to make use of it in one subsystem the [nomad](https://github.com/hashicorp/nomad) project, and if things go well I intend to expand our use of landlock to key features - including a new task driver based on it.

**Comment by gnoack** [comment]
Hello @shoenig!

I'm the author of https://github.com/landlock-lsm/go-landlock.

First of all, I am happy to hear that you are looking into using Landlock.

I'm still having trouble understanding what was missing in the existing go-landlock library, which prompted you to create an alternative one. It feels like we are duplicating work here, and using the same name as for the other library also makes it somewhat confusing.

I've put a lot of work into giving landlock-lsm/go-landlock the test coverage that it needs (regularly running against a list of kernels between 5.12 and 6.2-rc4), and into making it compatible with future versions of Landlock without breaking existing users. Both don't look like they are already addressed here? I can't keep you from doing this all over again, but I believe you would save yourself a lot of pain when using the existing library, or wrapping it.

## Regarding the things you identified as missing:

**Convenience helpers:** The existing go-landlock library doesn't support these yet, but would be able to support external convenience helpers as you are describing them (like `landlock.DNS()`, `landlock.Shared()` etc.), by exposing the generalized `restrictOpt` interface from https://github.com/landlock-lsm/go-landlock/commit/572d13278e8f48a4b5f77d1aeb9ef7cb9c153be2.

Would that help to adopt landlock-lsm/go-landlock library?

**Pledge-like interface:** I assume that this is also referring to the convenience helpers you defined, which have similar names to the [promises in `pledge`](https://man.openbsd.org/pledge.2)?

## Regarding other differences I see:

**Fall back to no-op on other OSs** - I think this is a good idea to do if the library is called in a "best effort" fashion (I think this corresponds to "Try" in your library?)

**Compatibility across different Landlock versions:** - landlock-lsm/go-landlock asks users to spell out which Landlock ABI they are aiming to use.  This lets users update their go-landlock library without changing the semantics of their code.  If the library just restricts the biggest possible set of access rights, the programs using the library might otherwise start misbehaving accidentally.  (Example: There is a patch in-flight for networking.)

## Summary

If we made it possible to use convenience helpers in landlock-lsm/go-landlock, you could create your distribution-specific convenience helpers in a `llutil` package, and you could presumably do the same things with a call like:

```
err := landlock.V3.BestEffort().RestrictPaths(
    llutil.DNS(),
    llutil.Shared(),
    // etc.
)
```

Would that work for you, to use the library that way?

In general, we are open for suggestions on what is missing - please reach out! :)
